### ISSUE TITLE
Data is not updating showing error status code 404

### ISSUE THREAD

**Issue by ARJ-HADES** [adrianhajdin/project_mern_memories#119]
Failed to load resource: the server responded with a status of 404 (Not Found)
posts.js:32 Error: Request failed with status code 404
    at createError (createError.js:16:1)
    at settle (settle.js:17:1)
    at XMLHttpRequest.handleLoad (xhr.js:61:1)

**Comment by ghost** [comment]
Hi, I'm stuck on the same issue, have you found any resources/solutions that may help with this issue?

**Comment by PARASnagpal99** [comment]
Same Error . Did You found any solutions .
