### ISSUE TITLE
createStore got deprecated

### ISSUE THREAD

**Issue by solodev02** [adrianhajdin/project_mern_memories#122]
![Screenshot 2022-06-19 135601](https://user-images.githubusercontent.com/107346203/174472448-faa82fb2-19aa-439b-a454-db72d61b9e31.png)
getting a error after installing react-toolkit 
because createStore function is no more present in the 'redux' module 
what to do?
it was told in the video that once we paste the json file we don't have to install anymore dependencies any more for client , may we this could be the reason for the error?
how to fix it.

**Comment by NgatiaJeffers** [comment]
Apparently, when you install the redux toolkit **createStore()** becomes depreciated, you can replace it with **configureStore()** which wraps **createStore()** to provide simplified configuration options.

A good example to config a store is:

**import React from 'react';**
**import ReactDOM from 'react-dom/client';**
**import { Provider } from 'react-redux';**
**import { configureStore } from "@reduxjs/toolkit";**

**import reducers from "./reducers";**

**import App from './App';**

**const store = configureStore({ reducer: reducers })**

you can check out the redux toolkit solution to **configureStore** 
[https://redux.js.org/usage/configuring-your-store#the-solution-configures]()

Hopefully this helps.

**Comment by EduardoBDonovan** [comment]
Getting the same issue... please advise with an example from the video ex(reducer, middleware, etc)

**Comment by nathanlao** [comment]
> Getting the same issue... please advise with an example from the video ex(reducer, middleware, etc)

I think this should work:

**import { Provider } from 'react-redux'; // initialize redux'**
**import { applyMiddleware, compose } from 'redux';**
**import { configureStore } from '@reduxjs/toolkit';**
**import thunk from 'redux-thunk';**
**import reducers from './reducers';**

**import App from './App';**

**const store = configureStore(reducers, compose(applyMiddleware(thunk)));**

**Comment by Gagenrllc** [comment]
Im tryign to get this to work myself and currently running into an error.

This is my source code.
`import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { applyMiddleware, compose} from 'redux';
import { configureStore } from '@reduxjs/toolkit';
import thunk from 'redux-thunk';

import reducers from './reducers';
import App from './App'

//const store = createStore(reducers,compose(applyMiddleware(thunk)))
const store = configureStore(reducers, compose(applyMiddleware(thunk)));
ReactDOM.render(
<Provider STORE={store}>
    <App />
</Provider>, document.getElementById('root'));`


and this is my error

`Uncaught Error: "reducer" is a required argument, and must be a function or an object of functions that can be passed to combineReducers
    at configureStore (configureStore.ts:149:1)
    at ./src/index.js (index.js:12:1)
    at __webpack_require__ (bootstrap:784:1)
    at fn (bootstrap:150:1)
    at 1 (styles.js:3:1)
    at __webpack_require__ (bootstrap:784:1)
    at checkDeferredModules (bootstrap:45:1)
    at Array.webpackJsonpCallback [as push] (bootstrap:32:1)
    at main.chunk.js:1:87
VM11:2 Uncaught ReferenceError: process is not defined
    at 4043 (<anonymous>:2:13168)
    at r (<anonymous>:2:306599)
    at 8048 (<anonymous>:2:9496)
    at r (<anonymous>:2:306599)
    at 8641 (<anonymous>:2:1379)
    at r (<anonymous>:2:306599)
    at <anonymous>:2:315627
    at <anonymous>:2:324225
    at <anonymous>:2:324229
    at e.onload (index.js:1:1)`

**Comment by Gagenrllc** [comment]
I'm stuck on this step as well.
The error im getting is this.

![image](https://user-images.githubusercontent.com/113944319/192613390-2d6bdc35-b9ed-4481-9868-6027b108a02e.png)


My code looks like this.

```
import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { applyMiddleware, compose} from 'redux';
import { configureStore } from '@reduxjs/toolkit';
import thunk from 'redux-thunk';

import reducers from './reducers';
import App from './App'

//const store = createStore(reducers,compose(applyMiddleware(thunk)))
const store = configureStore({reducer: reducers}, compose(applyMiddleware(thunk)));
//const store = configureStore({reducer: reducers});

ReactDOM.render(
<Provider STORE={store}>
    <App />
</Provider>, document.getElementById('root'));
```

**Comment by NgatiaJeffers** [comment]
> I'm stuck on this step as well. The error im getting is this.
> 
> ![image](https://user-images.githubusercontent.com/113944319/192613390-2d6bdc35-b9ed-4481-9868-6027b108a02e.png)
> 
> My code looks like this.
> 
> ```
> import React from 'react';
> import ReactDOM from 'react-dom';
> import { Provider } from 'react-redux';
> import { applyMiddleware, compose} from 'redux';
> import { configureStore } from '@reduxjs/toolkit';
> import thunk from 'redux-thunk';
> 
> import reducers from './reducers';
> import App from './App'
> 
> //const store = createStore(reducers,compose(applyMiddleware(thunk)))
> const store = configureStore({reducer: reducers}, compose(applyMiddleware(thunk)));
> //const store = configureStore({reducer: reducers});
> 
> ReactDOM.render(
> <Provider STORE={store}>
>     <App />
> </Provider>, document.getElementById('root'));
> ```

Apparently what I'm thinking is you are using the latest redux toolkit, 
Assuming that I would urge you to consider this solution

All the logic related to configuring the store - including importing reducers, middleware, and enhancers - is handled in a dedicated file in a configureStore function 

**import React from 'react';**
**import ReactDOM from 'react-dom/client';**
**import { Provider } from 'react-redux';**
**import { configureStore } from "@reduxjs/toolkit";**

**import reducers from "./reducers";**

**import App from './App';**

**const store = configureStore({ reducer: reducers })**

You could refer to the redux toolkit for more clarity.
https://redux.js.org/usage/configuring-your-store#the-solution-configurestore

**Comment by ghost** [comment]
For the record this has nothing to do with your actual application code. It is specifically a message to users like you who are using "plain Redux" - it's trying to tell you that you're following patterns that are much harder to use, and we want you to use Redux Toolkit instead because it will make your life much easier :)

You'll note that this isn't even a runtime warning being printed in the console - it's literally just a visual indicator in your editor, like createStore.

**Comment by AAdewunmi** [comment]
> > I'm stuck on this step as well. The error im getting is this.
> > ![image](https://user-images.githubusercontent.com/113944319/192613390-2d6bdc35-b9ed-4481-9868-6027b108a02e.png)
> > My code looks like this.
> > ```
> > import React from 'react';
> > import ReactDOM from 'react-dom';
> > import { Provider } from 'react-redux';
> > import { applyMiddleware, compose} from 'redux';
> > import { configureStore } from '@reduxjs/toolkit';
> > import thunk from 'redux-thunk';
> > 
> > import reducers from './reducers';
> > import App from './App'
> > 
> > //const store = createStore(reducers,compose(applyMiddleware(thunk)))
> > const store = configureStore({reducer: reducers}, compose(applyMiddleware(thunk)));
> > //const store = configureStore({reducer: reducers});
> > 
> > ReactDOM.render(
> > <Provider STORE={store}>
> >     <App />
> > </Provider>, document.getElementById('root'));
> > ```
> 
> Apparently what I'm thinking is you are using the latest redux toolkit, Assuming that I would urge you to consider this solution
> 
> All the logic related to configuring the store - including importing reducers, middleware, and enhancers - is handled in a dedicated file in a configureStore function
> 
> **import React from 'react';** **import ReactDOM from 'react-dom/client';** **import { Provider } from 'react-redux';** **import { configureStore } from "@reduxjs/toolkit";**
> 
> **import reducers from "./reducers";**
> 
> **import App from './App';**
> 
> **const store = configureStore({ reducer: reducers })**
> 
> You could refer to the redux toolkit for more clarity. https://redux.js.org/usage/configuring-your-store#the-solution-configurestore

Hey, tried your fix but it didnt work.

Check out my code par the same issue.

Will appreciate your assistance.

https://github.com/adrianhajdin/project_mern_memories/issues/177#issue-2028978845

**Comment by AAdewunmi** [comment]
FYI: @solodev02, @EduardoBDonovan, @Gagenrllc

**Issue fixed!**
If you are having issues with Redux createStore() being depreciated, here's how to use configureStore():

1. Run on server side console ->
# NPM
npm install @reduxjs/toolkit
# Yarn
yarn add @reduxjs/toolkit

2. Include configureStore() in your client/src/index.js file

```
import React from "react";
import ReactDOM from "react-dom";
import { Provider } from "react-redux";
// import { createStore, applyMiddleware, compose} from "redux";
// import thunk from "redux-thunk";
import { configureStore } from "@reduxjs/toolkit";
import reducers from "./reducers";
import App from "./App";
import "./index.css";

// const store = createStore(reducers, compose(applyMiddleware(thunk)));
const store = configureStore({ reducer: reducers });
ReactDOM.render(
    <Provider store={store}>
       <App />
    </Provider>,
  document.getElementById("root")
);
```

Job done!

![Screenshot 2023-12-25 at 10 11 16](https://github.com/adrianhajdin/project_mern_memories/assets/15172744/b9ac57d4-de4d-46ee-a0d1-308bda9cc453)

![Screenshot 2023-12-25 at 10 11 43](https://github.com/adrianhajdin/project_mern_memories/assets/15172744/e304f978-4cd7-4dfd-9e02-3b17d13fc20d)
