### ISSUE TITLE
Post.js:87 Uncaught TypeError: Cannot read properties of null (reading 'map')

### ISSUE THREAD

**Issue by HaominChenn** [adrianhajdin/project_mern_memories#142]
TypeError: Cannot read properties of null (reading 'map')
    at Post (Post.js:87:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at batchedUpdates$1 (react-dom.development.js:22387:1)
    at Object.notify (Subscription.js:19:1)
    at Subscription.notifyNestedSubs (Subscription.js:90:1)
    at Subscription.handleChangeWrapper (Subscription.js:95:1)
    at dispatch (redux.js:297:1)
    at index.js:11:1
    at dispatch (redux.js:659:1)
    at posts.js:15:1

I can not access all the posts, before that it is no issue!
TypeError: Cannot read properties of null (reading 'map')
Post
D:/JsMastery-MERN-project/client/src/components/Posts/Post/Post.js:87
   84 | 	)}
  85 | </div>
  86 | <div className={classes.details}>
> 87 | 	<Typography variant="body2" color="textSecondary">
     | ^  88 | 		{post.tags.map((tag) => `#${tag} `)}
  89 | 	</Typography>
  90 | </div>
▶ 23 stack frames were collapsed.
(anonymous function)
D:/JsMastery-MERN-project/client/src/actions/posts.js:15
  12 | try {
  13 | 	const { data } = await api.fetchPosts();
  14 | 
> 15 | 	dispatch({ type: FETCH_ALL, payload: data });
     | ^  16 | } catch (error) {
  17 | 	console.log(error);
  18 | }
View compiled

**Comment by HaominChenn** [comment]
I have fixed it, simply just change another new database and fix it.
