### ISSUE TITLE
TypeError: func.apply is not a function, when ever I navigate back from any particular post to home page it shows  this error and it doesn't actually shows where it is occurring,   

### ISSUE THREAD

**Issue by unseen703** [adrianhajdin/project_mern_memories#164]

**Comment by unseen703** [comment]
func.apply is not a function
TypeError: func.apply is not a function
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:42117:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:42161:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:42209:35)
    at safelyCallDestroy (http://localhost:3000/static/js/bundle.js:58944:9)
    at http://localhost:3000/static/js/bundle.js:59340:25
    at unstable_runWithPriority (http://localhost:3000/static/js/bundle.js:74440:16)
    at runWithPriority$1 (http://localhost:3000/static/js/bundle.js:51686:14)
    at commitUnmount (http://localhost:3000/static/js/bundle.js:59335:19)
    at unmountHostComponents (http://localhost:3000/static/js/bundle.js:59648:11)
    at commitDeletion (http://localhost:3000/static/js/bundle.js:59678:9)


I have completed whole project till part_6 and everything is working smoothly except this thing, any help would be appreciated
