### ISSUE TITLE
Can someone please help me with this error message

### ISSUE THREAD

**Issue by Raghav2709** [adrianhajdin/project_mern_memories#178]
![Screenshot (828)](https://github.com/adrianhajdin/project_mern_memories/assets/152988951/900339c3-d08a-4c5c-bcbe-aa8d32b2040b)
This happens when I try to sign up as a new person on memories website.(Authentication Problem)
Error Message - 
index.js:20 
 
 POST http://localhost:5000/user/signup 404 (Not Found)
auth.js:24 
AxiosError {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}
code
: 
"ERR_BAD_REQUEST"
config
: 
{transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}
message
: 
"Request failed with status code 404"
name
: 
"AxiosError"
request
: 
XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
response
: 
{data: '<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta char…e>Cannot POST /user/signup</pre>\n</body>\n</html>\n', status: 404, statusText: 'Not Found', headers: AxiosHeaders, config: {…}, …}
stack
: 
"AxiosError: Request failed with status code 404\n    at settle (http://localhost:3000/main.163b7d63dc2807d8e50b.hot-update.js:1572:12)\n    at XMLHttpRequest.onloadend (http://localhost:3000/main.163b7d63dc2807d8e50b.hot-update.js:266:66)"
[[Prototype]]
: 
Error

**Comment by swarnim-dev** [comment]
Can you please share the corresponding code of server-side that's handling the post request. I'd also like to add that '404' indicates 'non found', this may indicate that an endpoint is not **correctly** configured to /user/signup

**Comment by JyothsnaVellampalli** [comment]
@Raghav2709  check if you are running server on port 5000.

**Comment by shristiss** [comment]
hey, any updates? I am also stuck on this issue!

**Comment by Saibaba161** [comment]
I too am stuck here
